### ISSUE TITLE
Unknown dependencies

### ISSUE THREAD

**Issue by coronel-kittycannon** [bobbylight/TokenMakerMaker#12]
I've been trying to build this project for an hour. It seems that there are dependencies not included in the build.gradle or in RSTA. Anyway, these are the unresolved imports:

org.fife.help.HelpDialog;
org.fife.jgoodies.looks.common.ShadowPopupFactory;
org.fife.ui.CustomizableToolBar;
org.fife.ui.OS;
org.fife.ui.SplashScreen;
org.fife.ui.StatusBar;
org.fife.ui.app.AbstractGUIApplication;
org.fife.ui.app.AppAction;
org.fife.ui.rtextfilechooser.FileChooserOwner;
org.fife.ui.rtextfilechooser.RTextFileChooser;
org.fife.ui.rtextfilechooser.filters.ExtensionFileFilter;

net.java.balloontip.BalloonTip;
net.java.balloontip.styles.RoundedBalloonStyle;
net.java.balloontip.utils.FadingUtils;
net.java.balloontip.utils.TimingUtils;

**Comment by bobbylight** [comment]
This is no longer an issue, as all dependencies are now pulled from Maven Central.  Marking FIXED.
