### ISSUE TITLE
Build fails with errors

### ISSUE THREAD

**Issue by JamzTheMan** [bobbylight/TokenMakerMaker#9]
First issue is 2.6.0-SNAPSHOT files do not seem to exist.  I can pull 2.6.1-SNAPSHOT (or 2.6.0 regular build) and the fife.common seems to only have a 2.5.8-SNAPSHOT.

With these dependencies there are SEVERAL errors throughout the project. Looks like several classes were moved around?  Also, gradle throws a error: Could not find match for name 'withXml'

**Comment by bobbylight** [comment]
Finally cleaning this project up, albeit several years too late.  These issues should be resolved now, so I'm closing this ticket.
